### ISSUE TITLE
Proper place to initiate a db connection

### ISSUE THREAD

**Issue by skota** [jedireza/generator-hapi-style#14]
I am new to hapi and a node beginner. I installed the generator and have a skeleton api running. Where and how would i launch a db connection..?

my api structure looks like this...

server
--api
----models/
-------------/model1.js
------------/model2.js

thanks

**Comment by jedireza** [comment]
Thanks for opening an issue. Take a look at some of the boilerplate apps: http://hapijs.com/resources#Boilerplates
