### ISSUE TITLE
New generator

### ISSUE THREAD

**Issue by victorferraz** [jedireza/generator-hapi-style#15]
Hello. 
What about, create a new generator with models ( association example with some Orm), controller and view (option for choose other templates engines).
Thanks

**Comment by jedireza** [comment]
Thanks for opening an issue. Once we get past a the simple hello world examples, things get opinionated quickly. What you described reminds me of boilerplate apps. Take a look here:

http://hapijs.com/resources#Boilerplates

I created the [Frame](https://github.com/jedireza/frame) and [Aqua](https://github.com/jedireza/aqua) projects listed in that section.
