### ISSUE TITLE
Can you provide a basic example of adding plugin to api or app

### ISSUE THREAD

**Issue by imatefx** [jedireza/generator-hapi-style#19]
I am new to hapi js i was looking for a yeoman generator and i found yours, can you provide me a basic usage on how I can add

```yo hapi-style:plugin hapi-space-madness```

to 

```yo hapi-style:api hapi-fan-serve```

**Comment by jedireza** [comment]
Thanks for opening an issue. When using the plugin generator, you'd probably create an independent module that you'd publish to npm directly and then consume it in another project by `require`ing it.

But like in [Frame](https://github.com/jedireza/frame/) where everything is a plugin, you'll notice app specific plugins are part of the larger project.

I hope that helps.

**Comment by imatefx** [comment]
Thanks..
