### ISSUE TITLE
Add prompt for choosing between handlebars and jade as template engine

### ISSUE THREAD

**Issue by mischah** [jedireza/generator-hapi-style#25]
Hi,

this is not an issue but a question.

I needed too long to understand how to replace jade with handlebars because things in the generated app are slightly different to the basic samples provided by the [hapi views tutorial](http://hapijs.com/tutorials/views). Talking about that manifest config style …

So I just want to ask if you would accept a pull request for choosing between handlebars and jade.

Thanks

**Comment by jedireza** [comment]
Thanks for creating an issue. Besides the first time learning curve of the manifest style config, there really isn't much to change code-wise. And since it's so easy, I think having an option for choosing between the two is more work (and maintenance) than just expecting consumers to customize their apps.

But you bring up an important point. Not everyone is immediatly used to the manifest/confidence/glue approach to hapi apps. Maybe some documentation is in order. Would you be willing to draft a tutorial about so we can add it to the wiki?

**Comment by mischah** [comment]
Thanks for the fast answer.

I guess it was the mixture of the learning curve of the manifest style config and hapi itself. 
I’m new to both of them :blush: 

> I think having an option for choosing between the two is more work (and maintenance) than just expecting consumers to customize their apps.

Valid point.

> Would you be willing to draft a tutorial about so we can add it to the wiki?

I’m not sure if I’m the right guy for that because I’m not sure I’ve understood the whole thing.

- I think I’m pretty confident in using this confidence thing.
- But I’m not sure what glue is handeling.
- And I still have no clue why I should separate https://github.com/mischah/flickr-gallery/blob/master/config.js from https://github.com/mischah/flickr-gallery/blob/master/manifest.js

It would be supernice if you could enlighten me with the last point.

**Comment by jedireza** [comment]
I used `confidence` for both the `./config.js` and `./manifest.js` because I liked how it allows us to change the config based on environment.

 - `./manifest.js` - is to be consumed by `glue` or `rejoice`
 - `./config.js` - could be for any project wide (probably not related to hapi) config

**Comment by mischah** [comment]
Thank you very much :kissing_heart:

**Comment by jedireza** [comment]
The [hapi/discuss](https://github.com/hapijs/discuss) repo is also a great resource.

**Comment by mischah** [comment]
Thanks.

I now got that glue thing btw.
You’re right. It’s super easy – if you know what to do.

Maybe I reconsider drafting that tutorial :smile:
